### ISSUE TITLE
Set up project in Qt Creator Community

### ISSUE THREAD

**Issue by EmmanuelMess** [genonbeta/TrebleShot-Desktop#17]
Are there any instructions to set up project in Qt Creator Commutiny?

**Comment by velitasali** [comment]
It uses CMake, so it is platform-independent. I am using CLion, but it should also work on Visual Studio and Qt Creator. Are you having an issue?

**Comment by velitasali** [comment]
BTW JetBrains offers a 1-year free subscription for college students that you can use for any license requiring IDE that they are offering.

**Comment by EmmanuelMess** [comment]
Loaded it in CLion (I had it but though you had used CodeBlocks because of the "build_trebleshot.sh" file).

Thanks!

**Comment by EmmanuelMess** [comment]
Hey, sorry to bother you again, but I am having trouble installing the dependencies:

> TrebleShot-Desktop/src/ui/FileAdditionProgressDialog.cpp:23:10: fatal error: QtCore/QRandomGenerator: No existe el archivo o el directorio
 #include <QtCore/QRandomGenerator>
          ^~~~~~~~~~~~~~~~~~~~~~~~~

"No existe el archivo o el directorio" tanslates to "The file or directory doesn't exist".

I can't seem to find a solution on the internet.

**Comment by velitasali** [comment]
Which Qt version are you using? It shouldn't be smaller than 5.10 because it is the version QtRandomGenerator was introduced.

**Comment by EmmanuelMess** [comment]
> sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-bionic -y
> sudo apt-get -y install libkf5dnssd-dev qt511base cmake

Shows that qt511base is up to date.

**Comment by velitasali** [comment]
Hm, could it be somehow targeting the Qt version that lives in the 16.04's universe, which, I am guessing, is 5.5. 

Can you try running this command `sudo apt autoremove qtbase5-dev` ?

**Comment by EmmanuelMess** [comment]
Fixed! Thanks!
