### ISSUE TITLE
Error when trying to  run the package on fedora

### ISSUE THREAD

**Issue by baali-boudjemaa** [genonbeta/TrebleShot-Desktop#27]
error while loading shared libraries: libcoolsocket.so.0: cannot open shared object file: No such file or director

**Comment by velitasali** [comment]
I am guessing your coolsocket module is outdated. Could you run these?

```sh
git pull
cd libs/coolsocket
git pull
cd ../..
rm -rvf cmake-build-debug cmake-build-release
./build_trebleshot.sh
./cmake-build-*/trebleshot
```

**Comment by UddipakBhuyan** [comment]
I get the same issue on my arch linux machine
Running the commands given gives me the following output

`Building: release
./build_trebleshot.sh: line 9: qtchooser: command not found
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Qt 5.13.2
CMake Error at CMakeLists.txt:187 (add_subdirectory):
  The source directory

    /home/midone/pkg/TrebleShot-Desktop/libs/coolsocket

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/midone/pkg/TrebleShot-Desktop/cmake-build-release/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'trebleshot'.  Stop.
`
qtchooser conflicts with qt5-base package in arch so I couldn't get it to install

**Comment by velitasali** [comment]
@baali-boudjemaa  This happens due to how AppImage works. I recently separated coolsocket from the project and shared libraries are not built into the resulting AppImage expecting them to be present on the host system. I try to include it as a static library.

@UddipakBhuyan Please run `git submodule update --init` on the root directory of the project before building it.

**Comment by velitasali** [comment]
https://github.com/libcoolsocket/qt5/commit/fe47df96e5cd32f8ac1ac5c1713ddc1c0846cf45 fixes this. Closing this for now. Feel free to reopen if you face similar problems.
