### ISSUE TITLE
Alpha version for Windows?

### ISSUE THREAD

**Issue by mizzunet** [genonbeta/TrebleShot-Desktop#37]
No version of Trebleshot for Windows has been released yet, right?

**Comment by velitasali** [comment]
Please see the downloads: https://github.com/trebleshot/desktop/releases/tag/0.1.0-alpha2

**Comment by mizzunet** [comment]
> Please see the downloads: https://github.com/trebleshot/desktop/releases/tag/0.1.0-alpha2

Thank you
