### ISSUE TITLE
Missing dlls

### ISSUE THREAD

**Issue by horstle** [genonbeta/TrebleShot-Desktop#4]
Hi, I just tried the 0.1.0 build on Windows 10 Home (TrebleShot-0.1.0-installer.exe) and got multiple errors about missing .dll during first start:

- MSVCP140D.dll
- VCRUNTIME140D.dll
- ucrtbased.dll

I guess I need to install some version of Visual C++?

**Comment by velitasali** [comment]
Hi @horstle, I am relatively new to the development on Windows platform. My best guess is that your computer already contains MSVCP140.dll and the rest without the suffix letter 'd' under C:\\Windows\System32 but probably missing the ones with the 'd' which is basically debug versions of those. BTW This is 64-bit build, so I will also try to provide 32 bit version as well.

What I can suggest is install VC++ 2017 64-32 bit versions if not already installed.

Next builds will be release build and maybe then it might work.

**Comment by horstle** [comment]
Hi, you are right. I installed the next continuous build and now I am able to start the program. No need to install any additional VC++.
Since you mention a 32bit version: Currently by default it installs to "Program Files (x86)" which AFAIK would be the default for a 32bit app. This 64bit version should (if I'm not mistaken) rather be installed to "Program Files".
Can't test any further atm, but I think you're doing great work.

**Comment by velitasali** [comment]
> Since you mention a 32bit version: Currently by default it installs to "Program Files (x86)" which AFAIK would be the default for a 32bit app. This 64bit version should (if I'm not mistaken) rather be installed to "Program Files".

Yeah you are right, it is a problem with NSIS packaging. Will fix that as well.

> Can't test any further atm, but I think you're doing great work.
Thank you :)
